version: "3"
services:
    app:
        build: .
        ports: 
            - "5000:5000"
        volumes: 
            - "${PWD}/data:/data"
#    app_2:
#        build: .
#        ports:
#            - "5001:5000"
#        volumes:
#            - "${PWD}/data:/data"
