version: "3"
services:
#    app:
#        image: cs7ns6groupf:latest
#        build: .
#        ports:
#            - "5000:5000"
#        volumes:
#            - "${PWD}/data:/data"
    peer0:
        image: cs7ns6groupf:latest
        build: .
        ports:
            - "5000:5000"
            - "9000:9000"
        volumes:
            - "${PWD}/data/state_0.json:/data/state.json"
            - "${PWD}/data/test_0.db:/data/test.db"
        environment:
            SELF_ID: 0
            SELF: 0:peer0:9000
            PEERS: 1:peer1:9001 2:peer2:9002
            RAFT_STATE_PATH: /data/state.json
            DB_PATH: /data/test.db

    peer1:
        image: cs7ns6groupf:latest
        build: .
        ports:
            - "5001:5000"
            - "9001:9001"
        volumes:
            - "${PWD}/data/state_1.json:/data/state.json"
            - "${PWD}/data/test_1.db:/data/test.db"
        environment:
            SELF_ID: 1
            SELF: 1:peer1:9001
            PEERS: 0:peer0:9000 2:peer2:9002
            RAFT_STATE_PATH: /data/state.json
            DB_PATH: /data/test.db

    peer2:
        image: cs7ns6groupf:latest
        build: .
        ports:
            - "5002:5000"
            - "9002:9002"
        volumes:
            - "${PWD}/data/state_2.json:/data/state.json"
            - "${PWD}/data/test_2.db:/data/test.db"
        environment:
            SELF_ID: 2
            SELF: 2:peer2:9002
            PEERS: 0:peer0:9000 1:peer1:9001
            RAFT_STATE_PATH: /data/state.json
            DB_PATH: /data/test.db
