version: "3"
services:
#    app:
#        image: cs7ns6groupf:latest
#        build: .
#        ports:
#            - "5000:5000"
#        volumes:
#            - "${PWD}/data:/data"
    peer0:
        image: cs7ns6groupf:latest
        build: .
        ports:
            - "5000:5000"
            - "9000:9000"
        volumes:
            - "${PWD}/data:/data"
        environment:
            SELF_ID: 0
            SELF: 0:peer0:9000
            PEERS: 1:peer1:9001 2:peer2:9002

    peer1:
        image: cs7ns6groupf:latest
        build: .
        ports:
            - "5001:5000"
            - "9001:9001"
        volumes:
            - "${PWD}/data:/data"
        environment:
            SELF_ID: 1
            SELF: 1:peer1:9001
            PEERS: 0:peer0:9000 2:peer2:9002

    peer2:
        image: cs7ns6groupf:latest
        build: .
        ports:
            - "5002:5000"
            - "9002:9002"
        volumes:
            - "${PWD}/data:/data"
        environment:
            SELF_ID: 2
            SELF: 2:peer2:9002
            PEERS: 0:peer0:9000 1:peer1:9001

