version: "3"
services:
    toxiproxy:
        image: shopify/toxiproxy:latest
        ports:
            - "8474:8474"
    peer0:
        image: cs7ns6-groupf-ipc:latest
        build:
            context: .
            dockerfile: ipc.Dockerfile
        ports: 
            - "9000:9000"
        environment:
            PEER_ID: 0
            PEERS: peer0:9000 toxiproxy:19001 toxiproxy:19002
            QUORUM_WRITE: 2
            QUORUM_READ: 1
        depends_on:
          - toxiproxy
        
    peer1:
        image: cs7ns6-groupf-ipc:latest
        build:
            context: .
            dockerfile: ipc.Dockerfile
        ports: 
            - "9001:9001"
        environment:
            PEER_ID: 1
            PEERS: toxiproxy:19000 peer1:9001 toxiproxy:19002
            QUORUM_WRITE: 2
            QUORUM_READ: 1
        depends_on:
          - toxiproxy

    peer2:
        image: cs7ns6-groupf-ipc:latest
        build:
            context: .
            dockerfile: ipc.Dockerfile
        ports: 
            - "9002:9002"
        environment: 
            PEER_ID: 2
            PEERS: toxiproxy:19000 toxiproxy:19001 peer2:9002
            QUORUM_WRITE: 2
            QUORUM_READ: 1
        depends_on:
          - toxiproxy