version: "3"
services:
    peer0:
        image: cs7ns6-groupf-ipc:latest
        build:
            context: .
            dockerfile: ipc.Dockerfile
        ports: 
            - "9000:9000"
        environment:
            PEER_ID: 0
            PEERS: peer0:9000 peer1:9001 peer2:9002
        
    peer1:
        image: cs7ns6-groupf-ipc:latest
        build:
            context: .
            dockerfile: ipc.Dockerfile
        ports: 
            - "9001:9001"
        environment:
            PEER_ID: 1
            PEERS: peer0:9000 peer1:9001 peer2:9002

    peer2:
        image: cs7ns6-groupf-ipc:latest
        build:
            context: .
            dockerfile: ipc.Dockerfile
        ports: 
            - "9002:9002"
        environment: 
            PEER_ID: 2
            PEERS: peer0:9000 peer1:9001 peer2:9002

networks:
    cs7ns6-groupf-net:
